game_names = [
    'Fire-Bred',
    'Titanium',
    'Hurricane',
    'Ironsides',
    'Iron-Cut',
    'Tempest',
    'Iron Heart',
    'Steel Forge',
    'Pursuit',
    'Steel Foil',
    'Sick Rebellious Names',
    'Upsurge',
    'Uprising',
    'Overthrow',
    'Breaker',
    'Sabotage',
    'Dissent',
    'Subversion',
    'Rebellion',
    'Insurgent',
    'Accidental Genius',
    'Acid Gosling',
    'Admiral Tot',
    'AgentHercules',
    'Airport Hobo',
    'Alley Frog',
    'Alpha',
    'AlphaReturns',
    'Angel',
    'AngelsCreed',
    'Arsenic Coo',
    'Atomic Blastoid',
    'Automatic Slicer',
    'Baby Brown',
    'Back Bett',
    'Bad Bunny',
    'Bazooka Har-de-har',
    'Bearded Angler',
    'Beetle King',
    'Betty Cricket',
    'Bit Sentinel',
    'Bitmap',
    'BlacKitten',
    'Blister',
    'Blistered Outlaw',
    'Blitz',
    'BloodEater',
    'Bonzai',
    'BoomBeachLuvr',
    'Boom Blaster',
    'Bootleg Taximan',
    'Bowie',
    'Bowler',
    'Breadmaker',
    'Broomspun',
    'Buckshot',
    'Bug Blitz',
    'Bug Fire',
    'Bugger',
    'Cabbie',
    'Candy Butcher',
    'Capital F',
    'Captain Peroxide',
    'Celtic Charger',
    'Centurion Sherman',
    'Cereal Killer',
    'Chasm Face',
    'Wardon',
    'Vulture',
    'Unique Identity',
    'Ultimate Guide',
    'Tweek',
    'Tusk',
    'Trink',
    'Torpedo',
    'Titanium',
    'The Red Wolf',
    'The Purple Bear',
    'The Orange Frog',
    'The Green Tiger',
    'The Great Shark',
    'The Dark Horse',
    'The Brown Fox',
    'The Armor',
    'Team Arsenic',
    'Sythe',
    'Strong Position',
    'Stream Elements',
    'Steel Foil',
    'Sniper',
    'Snake',
    'Slaughter',
    'Sky Bully',
    'Skull Crusher',
    'Silver Stone',
    'Silver Eagle',
    'Sienna Princess',
    'Sidewalk Enforcer',
    'Shiver',
    'Sherwood Gladiator',
    'Seal Snake',
    'Schizo',
    'Scary Pumpkin',
    'Scare Stone',
    'Scalp',
    'Sandbox',
    'Saint La-Z-Boy',
    'Rubble',
    'Rooster',
    'Ronin',
    'Romance Guppy',
    'Roller Turtle',
    'Roar Sweetie',
    'Roadkill',
    'Roadblock',
    'Relative Performance',
    'Red Rhino',
    'Majesty',
    'Anomaly',
    'Malice',
    'Banshee',
    'Mannequin',
    'Belladonna',
    'Minx',
    'Beretta',
    'Mirage',
    'Black Beauty',
    'Nightmare',
    'Calypso',
    'Nova',
    'Carbon',
    'Pumps',
    'Cascade',
    'Raven',
    'Colada',
    'Resin',
    'Cosma',
    'Riveter',
    'Cougar',
    'Rogue',
    'Countess',
    'Roulette',
    'Enchantress',
    'Shadow',
    'Enigma',
    'Siren',
    'Femme Fatale',
    'Stiletto',
    'Firecracker',
    'Tattoo',
    'Geisha',
    'T-Back',
    'Goddess',
    'Temperance',
    'Half Pint',
    'Tequila',
    'Harlem',
    'Terror',
    'Heroin',
    'Thunderbird',
    'Infinity',
    'Ultra',
    'Insomnia',
    'Vanity',
    'Ivy',
    'Velvet',
    'Legacy',
    'Vixen',
    'Lithium',
    'Voodoo',
    'Lolita',
    'Wicked',
    'Lotus',
    'Widow',
    'Mademoiselle',
    'Funny Gaming Names',
    'Rotten Zucchini.',
    'Sandwich Deliveries.',
    'Sharks of Atlantis.',
    'Apple Bob.',
    'Clash of Cooks.',
    'Crayon Crime.',
    'Crazy Factory.',
    'Bananas n Chips.',
    'Call of Dowson.',
    'Candy Crush',
    'Candy Land',
    'Danknado',
    'Dodge the Shoe',
    'Fortnite Couch',
    'Gardening Gophers',
    'Grand Theft Auto',
    'Grandma’s Nose',
    'Horse Herpes',
    'James Bomb',
    'Kingdom of Memes',
    'Mario Kart',
    'Meme Man',
    'Minecraft',
    'Minecraft',
    'Mustache Smack',
    'My Little Balloon',
    'Nesting Hens',
    'Best Gaming Names',
    'Snow',
    'Serenity',
    'Nuzzle',
    'Climax',
    'Saki',
    'Eve',
    'Zlatan',
    'Remy',
    'Kiss',
    'Nana',
    'Belle',
    'Roses',
    'Cotton',
    'Gretchen',
    'Necromancer',
    'Rosalie',
    'Amy',
    'Kaylin',
    'Sakura',
    'Pudding',
    'Peach',
    'Rockstar',
    'Lily',
    'Karen',
    'Linda',
    'Badass Gaming Names',
    'Polaroid Pal',
    'Legend of Zelda',
    'Demonic Criminals',
    'Blistered Outlaw',
    'Super Mario',
    'Dooming',
    'Pigeon',
    'Bowser',
    'Inch',
    'Final Fantasy',
    'Orphan',
    'Aqua',
    'Inferior',
    'Invaders',
    'Numb',
    'Penguin',
    'Nest',
    'Unique Gaming Names',
    'Abducted by Aliens',
    'A Distraction',
    'Accidental Genius',
    'Admiral Tot',
    'Agent Hercules',
    'Airport Hobo',
    'Alley Frog',
    'Alpha Returns',
    'Angels Creed',
    'Arsenic Coo',
    'Atomic Blastoid',
    'Automatic Slicer',
    'Baby Brown',
    'Back Bett',
    'Bad Bunny',
    'Bazooka Har-de-har',
    'Bearded Angler',
    'Beetle King',
    'All Good Names Gone',
    'Ariana Grandes Ponytail',
    'Cupid Dust',
    'Daffy Girl',
    'Baby Doodles',
    'Bad Karma',
    'Banana Hammock',
    'Behind You',
    'Big Foot Is Real',
    'The Russian Spy',
    'Billy’s Mullet',
    'Blue Ivy’s Assistant',
    'Born Confused',
    'Bud Lightyear',
    'Calzone Zone',
    'Camelopard',
    'Casanova',
    'Cats Or Dogs',
    'Cereal Killer',
    'Cherry Picked',
    'Heisenbug',
    'Chin Chilin',
    'Chris P Bacon',
    'Colonel Mustards Rop',
    'Coolhunter',
    'Crazy Cat Lady',
    'Cuddly Puddly',
    'Cute As Ducks',
    'Darth Daenerys',
    'Definitely Not An Athlete',
    'Desperate Enuf',
    'Als',
]
