from .data import Tag

tags = [
    Tag(None, 'Indie'),
    Tag(None, 'Action'),
    Tag(None, 'Adventure'),
    Tag(None, 'Casual'),
    Tag(None, 'RPG'),
    Tag(None, 'Simulation'),
    Tag(None, 'Strategy'),
    Tag(None, 'Singleplayer'),
    Tag(None, 'Early Access'),
    Tag(None, 'Free to Play'),
    Tag(None, '2D'),
    Tag(None, '3D'),
    Tag(None, 'Atmospheric'),
    Tag(None, 'Fantasy'),
    Tag(None, 'Story Rich'),
    Tag(None, 'Colorful'),
    Tag(None, 'Multiplayer'),
    Tag(None, 'Puzzle'),
    Tag(None, 'Exploration'),
    Tag(None, 'Pixel Graphics'),
    Tag(None, 'Massively Multiplayer'),
    Tag(None, 'Cute'),
    Tag(None, 'Sports'),
    Tag(None, 'Violent'),
    Tag(None, 'First-Person'),
    Tag(None, 'Combat'),
    Tag(None, 'Racing'),
    Tag(None, 'Action-Adventure'),
    Tag(None, 'Anime'),
    Tag(None, 'Arcade'),
    Tag(None, 'Funny'),
    Tag(None, 'Sexual Content'),
    Tag(None, 'Nudity'),
    Tag(None, 'Sci-fi'),
    Tag(None, 'Shooter'),
    Tag(None, 'Relaxing'),
    Tag(None, 'Horror'),
    Tag(None, 'Family Friendly'),
    Tag(None, 'Gore'),
    Tag(None, 'Retro'),
    Tag(None, 'Third Person'),
    Tag(None, 'Controller'),
    Tag(None, 'Stylized'),
    Tag(None, 'Female Pro    Tagonist'),
    Tag(None, 'Open World'),
    Tag(None, 'Co-op'),
    Tag(None, 'Survival'),
    Tag(None, 'Platformer'),
    Tag(None, 'PvP'),
    Tag(None, 'Top-Down'),
    Tag(None, 'Choices Matter'),
    Tag(None, 'Realistic'),
    Tag(None, 'Comedy'),
    Tag(None, 'PvE'),
    Tag(None, 'Dark'),
    Tag(None, 'Visual Novel'),
    Tag(None, 'Character Customization'),
    Tag(None, 'Cartoony'),
    Tag(None, 'Physics'),
    Tag(None, 'Mystery'),
    Tag(None, 'Linear'),
    Tag(None, 'Multiple Endings'),
    Tag(None, '2D Platformer'),
    Tag(None, 'FPS'),
    Tag(None, 'Online Co-Op'),
    Tag(None, 'Old School'),
    Tag(None, 'Psychological Horror'),
    Tag(None, 'Difficult'),
    Tag(None, 'Magic'),
    Tag(None, 'VR'),
    Tag(None, 'Sandbox'),
    Tag(None, 'Tactical'),
    Tag(None, 'Medieval'),
    Tag(None, 'Action RPG'),
    Tag(None, 'Great Soundtrack'),
    Tag(None, 'Futuristic'),
    Tag(None, 'Minimalist'),
    Tag(None, 'Space'),
    Tag(None, 'Building'),
    Tag(None, 'Hand-drawn'),
    Tag(None, 'Point & Click'),
    Tag(None, 'Crafting'),
    Tag(None, 'Roguelike'),
    Tag(None, 'Management'),
    Tag(None, "Shoot 'Em Up"),
    Tag(None, 'Drama'),
    Tag(None, 'Cartoon'),
    Tag(None, 'Local Multiplayer'),
    Tag(None, 'Roguelite'),
    Tag(None, 'Design & Illustration'),
    Tag(None, 'Dark Fantasy'),
    Tag(None, 'Side Scroller'),
    Tag(None, 'Resource Management'),
    Tag(None, 'Procedural Generation'),
    Tag(None, '3D Platformer'),
    Tag(None, 'Logic'),
    Tag(None, 'Mature'),
    Tag(None, 'Survival Horror'),
    Tag(None, 'Choose Your Own Adventure'),
    Tag(None, 'Education'),
    Tag(None, 'Romance'),
    Tag(None, 'Puzzle Platformer'),
    Tag(None, 'Emotional'),
    Tag(None, 'Turn-Based Combat'),
    Tag(None, 'Immersive Sim'),
    Tag(None, 'Utilities'),
    Tag(None, 'Hack and Slash'),
    Tag(None, '1980s'),
    Tag(None, 'Turn-Based Strategy'),
    Tag(None, 'Interactive Fiction'),
    Tag(None, 'War'),
    Tag(None, 'Nature'),
    Tag(None, 'Turn-Based Tactics'),
    Tag(None, 'Hentai'),
    Tag(None, 'Zombies'),
    Tag(None, 'Post-apocalyptic'),
    Tag(None, 'Base Building'),
    Tag(None, 'Tabletop'),
    Tag(None, 'Action Roguelike'),
    Tag(None, 'Dating Sim'),
    Tag(None, 'Hidden Object'),
    Tag(None, "1990's"),
    Tag(None, 'Surreal'),
    Tag(None, 'Bullet Hell'),
    Tag(None, 'JRPG'),
    Tag(None, 'Local Co-Op'),
    Tag(None, 'Dungeon Crawler'),
    Tag(None, 'Stealth'),
    Tag(None, 'Party-Based RPG'),
    Tag(None, 'Historical'),
    Tag(None, 'Narration'),
    Tag(None, 'Walking Simulator'),
    Tag(None, 'Score Attack'),
    Tag(None, 'Replay Value'),
    Tag(None, 'NSFW'),
    Tag(None, 'Turn-Based'),
    Tag(None, 'Cinematic'),
    Tag(None, 'Military'),
    Tag(None, 'Third-Person Shooter'),
    Tag(None, 'Text-Based'),
    Tag(None, 'Conversation'),
    Tag(None, 'LGBTQ+'),
    Tag(None, 'Top-Down Shooter'),
    Tag(None, '2.5D'),
    Tag(None, 'Aliens'),
    Tag(None, 'Investigation'),
    Tag(None, 'Isometric'),
    Tag(None, 'Cyberpunk'),
    Tag(None, 'Robots'),
    Tag(None, 'Team-Based'),
    Tag(None, 'Web Publishing'),
    Tag(None, 'Nonlinear'),
    Tag(None, 'Dark Humor'),
    Tag(None, 'Memes'),
    Tag(None, 'Lore-Rich'),
    Tag(None, 'Inventory Management'),
    Tag(None, 'Card Game'),
    Tag(None, 'Life Sim'),
    Tag(None, 'Demons'),
    Tag(None, 'Tutorial'),
    Tag(None, 'RTS'),
    Tag(None, 'Artificial Intelligence'),
    Tag(None, 'Strategy RPG'),
    Tag(None, 'Clicker'),
    Tag(None, 'Real Time Tactics'),
    Tag(None, 'Thriller'),
    Tag(None, 'Psychological'),
    Tag(None, 'Abstract'),
    Tag(None, 'Economy'),
    Tag(None, 'Arena Shooter'),
    Tag(None, 'Perma Death'),
    Tag(None, 'Detective'),
    Tag(None, 'Supernatural'),
    Tag(None, 'Driving'),
    Tag(None, 'Modern'),
    Tag(None, 'Fast-Paced'),
    Tag(None, 'Board Game'),
    Tag(None, 'Animation & Modeling'),
    Tag(None, 'Precision Platformer'),
    Tag(None, 'Time Management'),
    Tag(None, 'Tower Defense'),
    Tag(None, 'Short'),
    Tag(None, 'Dystopian '),
    Tag(None, 'Software'),
    Tag(None, 'Loot'),
    Tag(None, 'Psychedelic'),
    Tag(None, 'Tactical RPG'),
    Tag(None, '4 Player Local'),
    Tag(None, 'Souls-like'),
    Tag(None, 'City Builder'),
    Tag(None, 'Flight'),
    Tag(None, 'Comic Book'),
    Tag(None, 'Wargame'),
    Tag(None, 'Classic'),
    Tag(None, 'Alternate History'),
    Tag(None, 'Music'),
    Tag(None, "Beat 'em up"),
    Tag(None, 'Metroidvania'),
    Tag(None, 'Soundtrack'),
    Tag(None, 'RPGMaker'),
    Tag(None, 'Destruction'),
    Tag(None, 'Moddable'),
    Tag(None, 'Game Development'),
    Tag(None, 'Collectathon'),
    Tag(None, 'Mythology'),
    Tag(None, 'Runner'),
    Tag(None, 'Level Editor'),
    Tag(None, 'Fighting'),
    Tag(None, 'Movie'),
    Tag(None, 'Grid-Based Movement'),
    Tag(None, 'Parkour'),
    Tag(None, 'Crime'),
    Tag(None, 'Idler'),
    Tag(None, 'Deckbuilding'),
    Tag(None, '2D Fighter'),
    Tag(None, 'Experimental'),
    Tag(None, 'CRPG'),
    Tag(None, 'Beautiful'),
    Tag(None, 'Class-Based'),
    Tag(None, 'Video Production'),
    Tag(None, 'Competitive'),
    Tag(None, 'MMORPG'),
    Tag(None, 'Audio Production'),
    Tag(None, 'Dark Comedy'),
    Tag(None, 'Philosophical'),
    Tag(None, 'Card Battler'),
    Tag(None, 'Gun Customization'),
    Tag(None, 'Twin Stick Shooter'),
    Tag(None, 'Science'),
    Tag(None, 'Cats'),
    Tag(None, 'Automobile Sim'),
    Tag(None, 'World War II'),
    Tag(None, 'Co-op Campaign'),
    Tag(None, 'Vehicular Combat'),
    Tag(None, 'Rhythm'),
    Tag(None, 'Swordplay'),
    Tag(None, '3D Fighter'),
    Tag(None, 'Capitalism'),
    Tag(None, 'Lovecraftian'),
    Tag(None, 'Dragons'),
    Tag(None, 'Grand Strategy'),
    Tag(None, 'Battle Royale'),
    Tag(None, 'Space Sim'),
    Tag(None, 'eSports'),
    Tag(None, 'America'),
    Tag(None, '6DOF'),
    Tag(None, '3D Vision'),
    Tag(None, 'Automation'),
    Tag(None, 'Noir'),
    Tag(None, 'Conspiracy'),
    Tag(None, 'Split Screen'),
    Tag(None, 'Creature Collector'),
    Tag(None, 'Match 3'),
    Tag(None, 'Parody '),
    Tag(None, 'Software Training'),
    Tag(None, 'Bullet Time'),
    Tag(None, 'Colony Sim'),
    Tag(None, 'Farming Sim'),
    Tag(None, 'Blood'),
    Tag(None, 'Quick-Time Events'),
    Tag(None, 'Trading'),
    Tag(None, 'Satire'),
    Tag(None, 'Mystery Dungeon'),
    Tag(None, 'Hero Shooter'),
    Tag(None, 'Dynamic Narration'),
    Tag(None, 'Looter Shooter'),
    Tag(None, 'Open World Survival Craft'),
    Tag(None, 'Character Action Game'),
    Tag(None, 'Time Manipulation'),
    Tag(None, 'Gothic'),
    Tag(None, 'Cooking'),
    Tag(None, 'Underground'),
    Tag(None, 'Word Game'),
    Tag(None, 'Agriculture'),
    Tag(None, 'Voxel'),
    Tag(None, 'Spectacle fighter'),
    Tag(None, 'Mining'),
    Tag(None, 'Political'),
    Tag(None, 'Steampunk'),
    Tag(None, 'Mechs'),
    Tag(None, 'Martial Arts'),
    Tag(None, 'Time Travel'),
    Tag(None, 'Combat Racing'),
    Tag(None, 'Addictive'),
    Tag(None, 'Hunting'),
    Tag(None, 'Illuminati'),
    Tag(None, 'Otome'),
    Tag(None, 'Dog'),
    Tag(None, 'Solitaire'),
    Tag(None, 'Auto Battler'),
    Tag(None, 'Pirates'),
    Tag(None, 'Asynchronous Multiplayer'),
    Tag(None, 'Vampire'),
    Tag(None, 'Tanks'),
    Tag(None, 'God Game'),
    Tag(None, 'MOBA'),
    Tag(None, 'Immersive'),
    Tag(None, 'Ninja'),
    Tag(None, 'Fishing'),
    Tag(None, 'FMV'),
    Tag(None, 'Hex Grid'),
    Tag(None, 'Trading Card Game'),
    Tag(None, 'Hacking'),
    Tag(None, 'Remake'),
    Tag(None, 'Photo Editing'),
    Tag(None, 'Narrative'),
    Tag(None, 'Action RTS'),
    Tag(None, 'Politics'),
    Tag(None, 'Mouse only'),
    Tag(None, 'Assassin'),
    Tag(None, 'Underwater'),
    Tag(None, '4X'),
    Tag(None, 'Superhero'),
    Tag(None, 'Faith'),
    Tag(None, 'Dinosaurs'),
    Tag(None, 'Cold War'),
    Tag(None, 'Episodic'),
    Tag(None, 'Real-Time'),
    Tag(None, 'Cult Classic'),
    Tag(None, 'Sokoban'),
    Tag(None, 'Epic'),
    Tag(None, 'Programming'),
    Tag(None, 'Political Sim'),
    Tag(None, 'Western'),
    Tag(None, 'Heist'),
    Tag(None, 'Transportation'),
    Tag(None, 'Cozy'),
    Tag(None, 'Party Game'),
    Tag(None, 'Party'),
    Tag(None, 'Diplomacy'),
    Tag(None, 'Archery'),
    Tag(None, 'Naval'),
    Tag(None, 'Trains'),
    Tag(None, 'Minigames'),
    Tag(None, 'Gambling'),
    Tag(None, 'Foreign'),
    Tag(None, 'Wholesome'),
    Tag(None, 'Snow'),
    Tag(None, 'Naval Combat'),
    Tag(None, 'Real-Time with Pause'),
    Tag(None, 'Transhumanism'),
    Tag(None, 'Roguelike Deckbuilder'),
    Tag(None, 'Typing'),
    Tag(None, 'Escape Room'),
    Tag(None, 'Sailing'),
    Tag(None, 'Touch-Friendly'),
    Tag(None, 'Villain Pro    Tagonist'),
    Tag(None, 'Dungeons & Dragons'),
    Tag(None, 'Sniper'),
    Tag(None, 'Traditional Roguelike'),
    Tag(None, 'Sequel'),
    Tag(None, 'On-Rails Shooter'),
    Tag(None, 'Mars'),
    Tag(None, 'Werewolves'),
    Tag(None, 'Nostalgia'),
    Tag(None, 'Music-Based Procedural Generation'),
    Tag(None, 'Offroad'),
    Tag(None, 'Time Attack'),
    Tag(None, 'Kickstarter'),
    Tag(None, 'Mod'),
    Tag(None, 'Trivia'),
    Tag(None, 'Football (Soccer)'),
    Tag(None, 'Horses'),
    Tag(None, 'Experience'),
    Tag(None, 'World War I'),
    Tag(None, '360 Video'),
    Tag(None, 'GameMaker'),
    Tag(None, 'Farming'),
    Tag(None, 'Boxing'),
    Tag(None, 'Games Workshop'),
    Tag(None, 'Jet'),
    Tag(None, 'Gaming'),
    Tag(None, 'Outbreak Sim'),
    Tag(None, 'Spaceships'),
    Tag(None, 'Chess'),
    Tag(None, 'Documentary'),
    Tag(None, 'Spelling'),
    Tag(None, 'Motorbike'),
    Tag(None, 'Unforgiving'),
    Tag(None, 'Medical Sim'),
    Tag(None, 'Silent Pro    Tagonist'),
    Tag(None, 'Asymmetric VR'),
    Tag(None, 'Golf'),
    Tag(None, 'Bikes'),
    Tag(None, 'LEGO'),
    Tag(None, 'Roguevania'),
    Tag(None, 'Submarine'),
    Tag(None, 'Rome'),
    Tag(None, 'Electronic Music'),
    Tag(None, 'Basketball'),
    Tag(None, 'Crowdfunded'),
    Tag(None, 'Ambient'),
    Tag(None, 'Social Deduction'),
    Tag(None, 'Football (American)'),
    Tag(None, 'Instrumental Music'),
    Tag(None, 'Pinball'),
    Tag(None, 'Skateboarding'),
    Tag(None, 'Mini Golf'),
    Tag(None, 'TrackIR'),
    Tag(None, 'Wrestling'),
    Tag(None, 'Warhammer 40K'),
    Tag(None, 'Jump Scare'),
    Tag(None, 'Rock Music'),
    Tag(None, 'Vikings'),
    Tag(None, 'Pool'),
    Tag(None, 'Baseball'),
    Tag(None, 'Based On A Novel'),
    Tag(None, 'Cycling'),
    Tag(None, 'Tennis'),
    Tag(None, 'Skating'),
    Tag(None, 'Intentionally Awkward Controls'),
    Tag(None, 'Job Simulator'),
    Tag(None, 'Motocross'),
    Tag(None, 'Boss Rush'),
    Tag(None, '8-bit Music'),
    Tag(None, 'Lemmings'),
    Tag(None, 'Tile-Matching'),
    Tag(None, 'Bowling'),
    Tag(None, 'Hockey'),
    Tag(None, 'Well-Written'),
    Tag(None, 'Hardware'),
    Tag(None, 'BMX'),
    Tag(None, 'ATV'),
    Tag(None, 'Snowboarding'),
    Tag(None, 'Steam Machine'),
    Tag(None, 'Benchmark'),
    Tag(None, 'Skiing'),
    Tag(None, 'Mahjong'),
    Tag(None, 'Electronic'),
    Tag(None, 'Extraction Shooter'),
    Tag(None, 'Voice Control'),
    Tag(None, 'Musou'),
    Tag(None, 'Birds'),
    Tag(None, 'Feature Film'),
    Tag(None, 'Shop Keeper'),
    Tag(None, 'Fox'),
    Tag(None, 'Coding'),
    Tag(None, 'Rugby'),
    Tag(None, 'Cricket'),
    Tag(None, 'Volleyball'),
    Tag(None, 'Hobby Sim'),
    Tag(None, 'Reboot'),
    Tag(None, 'Snooker')
]
